server:
  port: 10004
spring:
  application:
    name: myapi
  datasource:
    url: jdbc:mysql://10.26.1.89:3306/mydemo?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.example.cloud.domain
  mapper-locations: classpath*:/mapper/*.xml