server:
  port: 10004
spring:
  application:
    name: myapi
  datasource:
    url: jdbc:mysql://10.26.1.185:3306/mydemo?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  jackson:
      time-zone: GMT+8:00
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: use_defaults


mybatis:
  type-aliases-package: com.example.cloud.domain
  mapper-locations: classpath*:/mapper/*.xml
springfox:
  documentation:
    swagger:
      v2:
        path: /api-doc
